[graph]
all-features = true

[advisories]
yanked = "deny"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
]
confidence-threshold = 1.0

exceptions = [
    # Allow GPL-3.0 for the current workspace only
    { crate = "position-share", allow = ["GPL-3.0"] },
]

[bans]
wildcards = "deny"
highlight = "all"
